"""
Django settings for midnight project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-vw%kj(n%4u8q*y6k+b*ba4%#gi08d^n7%l+j+)5o41^o54%_w-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
import os
#STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
STATIC_URL = '/static/'
MEDIA_URL = '/media/'
# CSRF_TRUSTED_ORIGINS = ['http://*.merkl.it']
# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'home.apps.HomeConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'paypal.standard.ipn',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'midnight.urls'
STATICFILES_DIRS=[BASE_DIR/"static"]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'midnight.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'
authkey='414224A55H0hiV65a9421fP1'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/
# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
JAZZMIN_SETTINGS={
    # "site_logo":"static/assets/img/logo-navbar.png",
    "site_logo_classes":"img-circle",
    "site_icon":"Delights.png",
    "welcome_sign":"Welcome To Midnight Delights",
    "copyright":"Midnight Delights",
    "search_model": ["home.Customer", "home.Food_Category","home.Food_Item"],
    "topmenu_links": [

        # Url that gets reversed (Permissions can be added)
        {"name": "Home", "url": "admin:index","icons":"fas fa-house-user"},

        # external url that opens in a new window (Permissions can be added)
        # model admin to link to (Permissions checked against model)
        {"model": "home.Customer"},
        # App with dropdown menu to all its models pages (Permissions checked against models)
        {"app":"home"}
    ],
    "hide_models":"",
    "custom_links": {
        "home": [{
            "name": "Visit Our Website",
            "url": 'index',
            "icon": "fas fa-comments",

        }]
    },
"icons": {
    "auth.User":"far fa-user-circle",
    "auth.Group":"fas fa-layer-group",
    "home.Address":"far fa-address-book",
    "home.Area":"fas fa-warehouse",
    "home.Restaurant":"fas fa-store",
    "home.Customer":"far fa-user",
    "home.Offers":"fas fa-wallet",
    "home.Food_Category":"fas fa-utensils",
    "home.Food_Item":"fas fa-utensils",
    "home.SaleOrder":"fas fa-weight-hanging",
    "home.SaleOrder_Detail":"fas fa-shopping-cart",
    "home.Membership":"fas fa-user-shield",
    "home.Payment":"far fa-money-bill-alt",
    "home.Feedback":"fas fa-comments",
    },
"changeform_format": "carousel",
    "show_ui_builder":False
}
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_USE_SSL = True
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'nisargt1782@gmail.com'
EMAIL_HOST_PASSWORD="zamjxjhvgtzjojvu"
EMAIL_PORT = 587

PAYPAL_RECEIVER_EMAIL='midnightDelight2024@gmail.com'
PAYPAL_TEST = True

SECURE_CROSS_ORIGIN_OPENER_POLICY='same-origin-allow-popups'