# Generated by Django 4.2.4 on 2024-01-16 17:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Receiver_Name", models.CharField(max_length=15)),
                ("Receiver_Contact", models.CharField(max_length=10)),
                ("Landmark", models.TextField(unique=True)),
                (
                    "Address_type",
                    models.CharField(
                        choices=[("1", "Home"), ("2", "Office"), ("3", "Other")],
                        max_length=6,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "Pincode",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=6,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("Name", models.CharField(max_length=25, unique=True)),
                ("Latitude", models.FloatField()),
                ("Longitude", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("First_Name", models.CharField(max_length=15)),
                ("Last_Name", models.CharField(max_length=15)),
                ("Image", models.ImageField(null=True, upload_to="photos")),
                ("Contact", models.CharField(max_length=10, unique=True)),
                ("Email", models.EmailField(max_length=254, unique=True)),
                (
                    "Address_Landmark",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="home.address",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Food_Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=25, unique=True)),
                ("Image", models.ImageField(upload_to="photos")),
                (
                    "Subcategory",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="home.food_category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Food_Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=40, unique=True)),
                ("Description", models.TextField()),
                ("Price", models.IntegerField()),
                ("Food_Image", models.ImageField(upload_to="photos")),
                ("Jain_Food", models.BooleanField(default=False)),
                (
                    "Category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="home.food_category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Amount", models.IntegerField(default=499, editable=False)),
                ("Start_Date", models.DateField(auto_now_add=True)),
                ("End_Date", models.DateField()),
                (
                    "Customer_Name",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="home.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Offers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Description", models.TextField()),
                (
                    "Amount",
                    models.IntegerField(
                        validators=[django.core.validators.MaxValueValidator(300)]
                    ),
                ),
                ("Coupon_On_Food", models.BooleanField(default=False)),
                ("Coupon_On_Order", models.BooleanField(default=False)),
                ("Start_Date", models.DateField()),
                ("End_Date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="SaleOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateTimeField(auto_now_add=True)),
                ("IsCancel", models.BooleanField(default=False)),
                ("Payment_Status", models.BooleanField(default=False)),
                (
                    "Payment_Type",
                    models.CharField(
                        choices=[
                            ("1", "Cash On Delivery"),
                            ("2", "UPI"),
                            ("3", "Card"),
                        ],
                        max_length=10,
                    ),
                ),
                ("Tax", models.FloatField(default=9.5, editable=False)),
                (
                    "Customer_Name",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="home.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SaleOrder_Detail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MaxValueValidator(10)]
                    ),
                ),
                (
                    "Food_Item_Name",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="home.food_item",
                    ),
                ),
                (
                    "SaleOrder_Id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="home.saleorder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateField(auto_now_add=True)),
                (
                    "Customer_Name",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="home.customer",
                    ),
                ),
                (
                    "Membership_Id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="home.membership",
                    ),
                ),
                (
                    "SaleOrder_Id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="home.saleorder",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="food_item",
            name="Offer_Name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="home.offers",
            ),
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("Date", models.DateField(auto_now_add=True)),
                ("Description", models.TextField()),
                (
                    "Customer_Name",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="home.customer",
                    ),
                ),
                (
                    "Food_Item_Name",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="home.food_item",
                    ),
                ),
                (
                    "SaleOrder_Id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="home.saleorder",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="address",
            name="Area_Pincode",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="home.area"
            ),
        ),
    ]
