# Generated by Django 4.2.4 on 2024-01-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food_category",
            name="Name",
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
    ]
