# Generated by Django 4.2.4 on 2024-01-16 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_alter_food_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food_category",
            name="Subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="home.food_category",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="Start_Date",
            field=models.DateField(),
        ),
    ]
