# Generated by Django 4.2.4 on 2024-01-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_alter_food_category_subcategory_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="End_Date",
            field=models.DateField(editable=False),
        ),
    ]
