# Generated by Django 4.2.4 on 2024-01-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_alter_membership_end_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(default="MidNight Delights", max_length=25)),
                ("Address", models.TextField()),
                ("OpenAt", models.CharField(max_length=10)),
                ("CloseAt", models.CharField(max_length=10)),
                ("OwnerName", models.CharField(max_length=15)),
                ("Contact", models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
    ]
