# Generated by Django 4.2.4 on 2024-01-17 15:26

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_alter_offers_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food_category",
            name="Image",
            field=models.ImageField(
                upload_to="photos", validators=[home.models.validate_image_extension]
            ),
        ),
    ]
