# Generated by Django 4.2.4 on 2024-01-17 15:34

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_alter_food_category_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="Receiver_Contact",
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="food_item",
            name="Food_Image",
            field=models.ImageField(
                upload_to="photos", validators=[home.models.validate_image_extension]
            ),
        ),
    ]
