# Generated by Django 4.2.4 on 2024-01-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_alter_address_receiver_contact_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="otp",
            field=models.CharField(max_length=4, null=True),
        ),
    ]
