# Generated by Django 4.2.4 on 2024-01-26 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0012_remove_customer_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="Address_Landmark",
        ),
        migrations.AddField(
            model_name="address",
            name="Customer_name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="home.customer",
            ),
        ),
    ]
