# Generated by Django 4.2.4 on 2024-01-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0015_rename_image_customer_cus_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="cus_Image",
        ),
        migrations.AddField(
            model_name="customer",
            name="img",
            field=models.URLField(null=True),
        ),
    ]
