# Generated by Django 4.2.4 on 2024-01-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0016_remove_customer_cus_image_customer_img"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="img",
        ),
        migrations.AddField(
            model_name="customer",
            name="cus_Image",
            field=models.ImageField(null=True, upload_to="photos"),
        ),
    ]
