# Generated by Django 4.2.4 on 2024-03-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0019_alter_address_landmark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="Landmark",
            field=models.TextField(unique=True),
        ),
    ]
