# Generated by Django 4.2.4 on 2024-03-04 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0023_alter_saleorder_payment_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order_Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateTimeField(auto_now=True)),
                (
                    "Status",
                    models.CharField(
                        choices=[
                            ("1", "Waiting for Accept"),
                            ("2", "Accepted"),
                            ("3", "Start Cooking"),
                            ("4", "Packaged"),
                            ("5", "Ready for Delivery"),
                            ("6", "Out for delivery"),
                            ("7", "Delivered"),
                            ("8", "Canceled"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "SaleOrder_Id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="home.saleorder",
                    ),
                ),
            ],
        ),
    ]
