# Generated by Django 4.2.4 on 2024-03-05 04:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0025_saleorder_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saleorder",
            name="location",
            field=models.URLField(max_length=500, null=True),
        ),
    ]
